import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>ClassCommit</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/classcommit.svg" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-white dark:bg-slate">
				
			</main>
		</>
	);
}